### ISSUE TITLE
Output no longer works on Linux via Wine

### ISSUE THREAD

**Issue by jere-mie** [kilbouri/Irvine32-Plus-Plus#4]
When using this library with wine, no output is displayed anymore. I believe this is because you hardcoded fd 11 as the source to write to, as opposed to getting the fd from the relevant syscall

**Comment by kilbouri** [comment]
Resolved by using `consoleOutHandle`, which is initialized using `GetStdHandle`, instead of a hard-coded `-11` as the file handle.

Change applied in [this commit](https://github.com/kilbouri/Irvine32-Plus-Plus/commit/4d5da6e49acab0deec2e206b1a46abfb801ba7ab)
